env:
  browser: true
  es2021: true
  jest: true
extends: airbnb-base
overrides: []
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules: {
  import/extensions: [0, {  <js>: "always"  }],
  no-underscore-dangle: 0,
  fp/no-mutating-methods: ["error", {
      "allowedObjects": ["array"]
    }]
}
